config/routes.rb
Test4::Application.routes.draw do

  root 'films#index'

  get 'index', to: 'films#index'

  get 'update', to: 'films#tabletime_update'

  

end

app/models/film.rb
class Film < ActiveRecord::Base
    has_many :seances, dependent: :destroy

    def self.tabletime_update
        Film.all.each {|e| e.delete}
        get_from_gorizont
        get_from_kado
    end


    def self.push_to_base shedule
        shedule.each_key do |key|
            if key == :cinema 
                next
            end

            film = Film.new(title: key, cinema: shedule[:cinema])
            film.save
            
            seances = shedule[key]
            seances.each  do |s|
                seance = Seance.new(begin_at: s) 
                seance.film = film
                seance.save
            end
        end
    end


    def self.get_from_kado
        agent = Mechanize.new
        url = "http://www.gold-cinema.ru/index.php?option=com_content&view=article&id=75&Itemid=80"

        films = agent.get(url).search(".//table[@width='600']").search(".//td[@valign='top']")

        shedule = {}
        films.each do |film|
            title = film.search(".//td[@width='300']").search(".//a").text

            shedules = []
            film.search(".//td[@style='font-size: 14pt;']").search(".//font").each do |shedule_item|
                line = shedule_item.text.strip
                shedules << line if (line.length > 0) 
            end
            shedule.merge!({title => shedules})
        end
        shedule.merge!({ :cinema => "Кадо(Голд синема)"}) # допишем имя кинотеатра 

        self.push_to_base(shedule)
    end


    def self.get_from_gorizont
        agent = Mechanize.new
        url = 'http://www.horizont-cinema.ru'
        
        films = agent.get(url).search(".//div[@class='af_category_item']")
        
        shedule = {}
        films.each do |film|
            title = film.search(".//div[@class='event_name']").children.children.children.text

            shedule_title = []
            film.search(".//span[@id='msg_rpice']").each do |time|
                #shedule_title << "#{time.children[0].text} #{time.children[1].children[2].text}"
                shedule_title << "#{time.children[0].text}"
            end
            title[0,2] = '' # удаляем из названия нумерацию и 1 точку  
            shedule.merge!({title => shedule_title})
        end
        shedule.merge!({ :cinema => "к-тр Горизонт"}) # допишем имя кинотеатра 
        
        self.push_to_base(shedule)
    end


end

app/models/seance.rb
class Seance < ActiveRecord::Base
  belongs_to :film
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    #Film.tabletime_update
    @films = Film.all
  end

  def tabletime_update
    Film.tabletime_update
    redirect_to action: 'index'
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
       format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<h1>Коломна. Фильмы сегодня</h1>

<table cellpadding="4"  border="1">
  <thead>
    <tr>
      <th>Кинотеатр</th>
      <th>Фильм</th>
      <th>Сеансы</th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.cinema %></td>
        <td><%= film.title %></td>
        <td>
          <% film.seances.each do |seance| %>
             <%= seance.begin_at %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Обновить список фильмов', update_path %>

<br>

<br> 

<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t52.6;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров и"+
" посетителей за 24 часа' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->

app/views/films/new.html.erb
<h1>New film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Фильмы сегодня</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>